In [5]:
import numpy as np

from time import time

from population import Population

# Test

In [2]:
TEST_population = Population(52)

In [3]:
result = TEST_population.calculate_values()
result

[[-0. -0.  0. ... -0.  0.  0.]
 [-0.  0.  0. ... -0.  0. -0.]
 [-0. -0. -0. ... -0.  0. -0.]
 ...
 [ 0.  0. -0. ... -0. -0.  0.]
 [-0.  0.  0. ... -0.  0. -0.]
 [ 0. -0.  0. ... -0. -0.  0.]]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]
[[ 0. -0. -0.  0. -0.  0. -0. -0. -0. -0. -0.  0. -0. -0. -0. -0. -0. -0.
  -0. -0. -0.  0. -0. -0.  0. -0.]
 [ 0. -0.  0.  0. -0. -0.  0. -0.  0.  0. -0.  0. -0. -0. -0.  0.  0. -0.
   0. -0. -0.  0.  0.  0. -0. -0.]
 [ 0. -0.  0. -0.  0. -0. -0. -0.  0.  0.  0.  0. -0. -0. -0. -0.  0.  0.
   0. -0. -0. -0. -0.  0. -0.  0.]
 [ 0. -0. -0.  0.  0. -0. -0. -0. -0.  0. -0. -0.  0. -0. -0.  0.  0. -0.
   0. -0. -0. -0. -0.  0.  0. -0.]
 [-0.  0. -0.  0. -0. -0.  0. -0. -0. -0.  0.  0. -0.  0. -0. -0.  0. -0.
  -0.  0. -0. -0. -0.  0. -0.  0.]
 [ 0. -0.  0.  0. -0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [4]:
print(TEST_population.layers[0]["values"])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
